// Bilingual content dictionary.
// German uses Swiss writing rules: no ß (use ss), apostrophe thousands separator
// (CHF 50'000), informal "du" voice throughout. Tech terms stay English where
// they're standard in Swiss/DE startup contexts (Pre-Seed, Pitch Deck, Cap
// Table, SAFE, Agentic OS, etc.).

import type { Lang } from "./lang";

const en = {
  common: {
    apply: "Apply",
    applyArrow: "Apply →",
    continue: "Continue",
    back: "Back",
    edit: "Edit",
    saved: "Saved",
    pressEnter: "Press",
    enterToContinue: "to continue",
    optional: "optional",
    sending: "Sending…",
    submit: "Submit application",
    backToSite: "← Back to site",
  },
  header: {
    manifesto: "Manifesto",
    stack: "Stack",
    tiers: "Tiers",
    toolkit: "Toolkit",
    process: "Process",
    portfolio: "Portfolio",
    terms: "Terms",
  },
  hero: {
    eyebrow: "The blankcollar family · Pre-Seed",
    h1a: "AI changed what",
    h1b: "founders build.",
    h2: "We changed what VCs deliver.",
    sub1: "We're the pre-seed VC arm of blankcollar — built for the AI era, based in Switzerland. Up to ",
    subAmount: "CHF 50'000",
    sub2: " in capital, the knowledge from ",
    sub3: ", and a fully-configured ",
    sub4: ".",
    primaryCta: "Apply for funding",
    secondaryCta: "Read the manifesto",
    backedLabel: "Backed:",
  },
  marquee: [
    "Pre-seed cheques up to CHF 50'000",
    "Decisions in 14 days",
    "Knowledge from theblankcollar.com",
    "Free, configured seat on blankcollar.ai",
    "Pitch deck, data room, business model — co-built",
    "Hands-on, not hands-off",
  ],
  stats: {
    cheque: "Cheque size",
    decision: "Decision time",
    toolkit: "Toolkit modules",
    agents: "Always-on agents",
  },
  manifesto: {
    eyebrow: "01 — Manifesto",
    h1: "Most pre-seed funds wire money",
    h2: "and disappear.",
    h3: "We do the opposite.",
    p1a: "The biggest problem founders face isn't getting the cheque. It's the pitch deck, the data room, the business model, the first hires, the pricing — the things first-time founders shouldn't have to figure out alone, but always do.",
    p2a: "blankcollar.vc writes the cheque, then gives you the knowledge from ",
    p2b: " and configures ",
    p2c: " — our agentic OS — for your company. We don't do the work for you. We make sure you can.",
  },
  founders: {
    eyebrow: "02 — Behind the fund",
    h1: "We're not",
    h2: "career investors.",
    p1: "blankcollar.vc is run by founders who built, scaled, and exited their own startups. We sat through the pitch reviews, lost the term sheets, hired the wrong first three engineers, and finally figured out what actually moves the needle.",
    p2: "Now we invest what we wish we'd had: a cheque, the playbooks for the hard things, and an OS that codifies it all so you don't spend year one re-learning what we already know.",
    milestones: [
      { stage: "Built", body: "Started companies from a spare laptop and a one-page deck." },
      { stage: "Scaled", body: "Wrote the first JD, the first SAFE, the first investor email." },
      { stage: "Exited", body: "Closed the round, sold the company, paid out the cap table." },
      { stage: "Now", body: "Investing what we wish we'd had on day zero." },
    ],
  },
  stack: {
    eyebrow: "03 — The Stack",
    h1: "One application.",
    h2: "Three layers of leverage.",
    sub: "Built like an OS. Capital makes the next layer possible. Knowledge makes the layer above it useful. Agents make all of it scale.",
    youAreHere: "● You are here",
    together: "Together = a complete startup",
    layers: [
      { label: "L3", name: "Agentic OS", site: "blankcollar.ai", voice: "bot", description: "We set up your agentic OS so the knowledge above runs as automation, not advice." },
      { label: "L2", name: "Knowledge", site: "theblankcollar.com", voice: "human", description: "Hands-on help on the things first-time founders shouldn't have to figure out alone." },
      { label: "L1", name: "Capital", site: "blankcollar.vc", voice: "human", description: "Up to CHF 50'000, pre-seed, founder-friendly terms.", current: true },
    ],
  },
  tiers: {
    eyebrow: "04 — How we work",
    h1: "Two ways we work.",
    h2: "We pick the fit.",
    sub1: "Every founder we back gets the knowledge from theblankcollar.com and a configured seat on blankcollar.ai. Whether we also write the cheque — up to CHF 50'000 — depends on your stage. We decide which fit makes sense once we've read your application.",
    cards: [
      {
        id: "access",
        name: "The Access",
        audience: "For founders who already have capital",
        capital: "Knowledge + OS",
        features: [
          "Full access to theblankcollar.com playbooks",
          "Configured seat on blankcollar.ai — your agentic OS",
          "Pitch deck, data room, business model — co-built",
          "Warm intros to seed / Series A when ready",
        ],
      },
      {
        id: "full-stack",
        name: "The Full Stack",
        audience: "For founders who need the lift",
        capital: "Up to CHF 50'000 + everything in The Access",
        features: [
          "Up to CHF 50'000 on a founder-friendly SAFE",
          "Full access to theblankcollar.com playbooks",
          "Configured seat on blankcollar.ai — your agentic OS",
          "Pitch deck, data room, business model — co-built",
          "Warm intros to seed / Series A when ready",
        ],
        emphasis: true,
      },
    ],
    ctaBody: "Not sure which fits? That's the point of the application — tell us what you're building, and we'll come back with our read.",
    ctaLink: "Send us your application",
  },
  toolkit: {
    eyebrow: "05 — The First-Time Founder Toolkit",
    h1: "The hard things you",
    h2: "don't have to figure out alone.",
    sub1: "Eight modules we co-build with you in the first weeks. We share what we've learned, then we wire it into your ",
    sub2: " agents so it keeps compounding.",
    items: [
      { label: "Pitch deck", body: "Story arc, deck design, the seven slides every fund actually reads." },
      { label: "Data room", body: "Cap table, contracts, KPIs, hiring docs — clean from day one." },
      { label: "Business model", body: "Pricing, unit economics, where margin actually comes from." },
      { label: "Cap table & SAFEs", body: "Founder splits, pool, conversions — clean equity from the first ticket." },
      { label: "Fundraising plan", body: "Target list, sequencing, the right narrative for each fund." },
      { label: "Hiring playbook", body: "JDs, comp benchmarks, where to source the first 5 hires." },
      { label: "Customer discovery", body: "Interview script, what to ignore, when to stop talking." },
      { label: "Pricing & packaging", body: "Tiers, anchoring, the pricing page that converts." },
    ],
  },
  network: {
    eyebrow: "06 — In practice",
    h1: "You at the centre.",
    h2: "Knowledge around you.",
    h3: "Agents inside the OS.",
    p: "Day one, you're no longer guessing. We share what works across ten domains every founder eventually needs, then we configure your agents on ",
    p2: " so the knowledge runs as automation.",
    knowledgeLabel: "Knowledge",
    knowledgeBody: " — pitch deck, data room, business model, fundraising, hiring, sales, pricing, finance, legal, brand.",
    agentsLabel: "Agents",
    agentsBody: " — research, outreach, ops, reporting, support. Configured for your stack.",
    legendKnowledge: "Knowledge we share (human)",
    legendAgents: "Agents we set up (bot)",
    knowledgeNodes: ["Pitch deck", "Data room", "Business model", "Fundraising", "Hiring", "Sales", "Pricing", "Finance", "Legal", "Brand"],
    agentNodes: ["agent.research", "agent.outreach", "agent.ops", "agent.report", "agent.support"],
    centerLabel: "FOUNDER",
    centerSub: "● YOU",
  },
  process: {
    eyebrow: "07 — Process",
    h1: "No deck. No warm intro.",
    h2: "Five steps. Two weeks.",
    steps: [
      { n: "01", label: "Apply", body: "Send us a paragraph and a link. No deck required, no warm intro needed.", detail: "~5 min" },
      { n: "02", label: "Decision", body: "We respond in 14 days max. Yes, no, or honest reason why.", detail: "≤ 14 days" },
      { n: "03", label: "Capital wired", body: "Up to CHF 50'000, founder-friendly terms. SAFE or equivalent.", detail: "≤ CHF 50'000" },
      { n: "04", label: "Knowledge transfer", body: "We sit with you on the hard stuff — pitch deck, data room, business model, hiring.", detail: "Week 1+" },
      { n: "05", label: "OS configured", body: "We set up blankcollar.ai for you. Your agents, your memory, codifying our knowledge.", detail: "Free, forever" },
    ],
    stepLabel: "Step",
  },
  compare: {
    eyebrow: "08 — vs Traditional pre-seed",
    h1: "Same money.",
    h2: "Different fund.",
    sub: "The difference isn't cheque size. It's what arrives the day after.",
    headerFeature: "Feature",
    headerTrad: "Traditional pre-seed",
    headerUs: "blankcollar.vc",
    rows: [
      { feature: "Cheque size", trad: "CHF 50'000 – 250'000 (often diluted)", us: "Up to CHF 50'000, founder-friendly" },
      { feature: "Decision time", trad: "Weeks of meetings", us: "14 days, max" },
      { feature: "After the wire", trad: "Quarterly check-ins", us: "Hands-on help on the hard things" },
      { feature: "Pitch deck & data room", trad: "“Send us when ready”", us: "Co-built with you, week one" },
      { feature: "Business model help", trad: "Intros to advisors", us: "Pricing, unit economics, moats" },
      { feature: "AI / automation", trad: "“Have you tried ChatGPT?”", us: "We set up blankcollar.ai for you" },
      { feature: "Hiring help", trad: "Intros to recruiters", us: "Playbooks, JDs, comp benchmarks" },
      { feature: "Board involvement", trad: "Observer seat", us: "None at this stage" },
      { feature: "Network", trad: "LP intros", us: "Knowledge + agents + portfolio" },
    ],
    inlineTradLabel: "Traditional ·",
  },
  portfolio: {
    eyebrow: "09 — Portfolio",
    h1: "Founders we've helped",
    h2: "scale from start to finish.",
    sub1: "Five Swiss / EU companies built on the same playbook: capital, knowledge, and an agentic OS — all wired in from day one. ",
    sub2: "One exit so far. Four still climbing.",
    statusActive: "Active",
    statusExited: "Exited",
    companies: [
      { name: "Numarics", domain: "numarics.com", url: "https://numarics.com", category: "Fintech / Accounting", body: "AI-native accounting for SMEs and fiduciary partners. Built, scaled, exited — now powering its successor, Money Key.", origin: "CH", status: "exited" as const },
      { name: "Cybee.ai", domain: "cybee.ai", url: "https://cybee.ai", category: "Cybersecurity", body: "Cybersecurity & compliance for SMBs. SOC 2, GDPR, ISO 27001 — automated, in plain language.", origin: "CH", status: "active" as const },
      { name: "iQTax", domain: "iqtax.ch", url: "https://iqtax.ch", category: "AI Tax", body: "The AI platform for Swiss tax declarations. Upload, file, done — in minutes, not hours.", origin: "CH", status: "active" as const },
      { name: "Alletta", domain: "alletta.ch", url: "https://alletta.ch", category: "InsurTech", body: "First fully digital, AI-powered health & legal insurance platform in Switzerland.", origin: "CH", status: "active" as const },
      { name: "Visorway", domain: "visorway.ai", url: "https://visorway.ai", category: "AI Consulting", body: "AI-native consulting. One AI advisor in front of full IT and ESG advisory engines.", origin: "EU", status: "active" as const },
    ],
  },
  netSection: {
    eyebrow: "10 — FYI",
    h1: "We know a lot",
    h2: "of investors.",
    p1: "Not a sales pitch — just useful to know. After years of building and exiting our own startups, we've kept the contacts: seed funds, Series A, family offices, the right angels.",
    p2: "We don't co-invest, and we're not selling a “network.” But when you're ready to raise the next round, we'll make warm intros to the right ones — directly, not via a portal.",
    stats: [
      { n: "Direct", label: "Relationships, not a portal" },
      { n: "Pre-seed → B", label: "Across follow-on stages" },
      { n: "Warm only", label: "We make the intro, not you" },
    ],
  },
  terms: {
    eyebrow: "11 — Terms",
    h1: "What you get,",
    h2: "in plain English.",
    rows: [
      { k: "Cheque", v: "Up to CHF 50'000" },
      { k: "Stage", v: "Pre-seed / Day 0" },
      { k: "Geography", v: "Global, remote-first" },
      { k: "Speed", v: "Decisions in 14 days" },
      { k: "Ownership", v: "Founder-friendly terms" },
      { k: "Plus", v: "Knowledge + Agentic OS" },
    ],
  },
  cta: {
    badge: "Now reviewing applications",
    h1a: "Building",
    h1b: "something?",
    h2a: "We'd love to",
    h2b: "help.",
    sub: "One paragraph, one link. If it's a fit, we'll move fast — capital, knowledge, and the OS, ready to deploy.",
    primary: "Start your application",
    secondary: "See the portfolio",
  },
  footer: {
    tagline: "The pre-seed fund of the blankcollar family. Capital, knowledge, and an agentic OS — in one cheque.",
    family: "Family",
    page: "Page",
    contact: "Contact",
    pageItems: ["Manifesto", "Stack", "Toolkit", "Portfolio", "Terms"],
    motto: "Work is for bots. Life is for humans.",
  },
  apply: {
    eyebrow: "Application",
    title: "Tell us what you're building.",
    sub: "~7 minutes. Auto-saves as you go. We respond in 14 days max — yes, no, or an honest reason why.",
    sectionsLabels: { you: "You", team: "Team", company: "Company", vision: "Vision", ask: "Ask", materials: "Materials", review: "Review" },
    stepOf: "Step",
    of: "of",
    feedback: {
      basics: "Quick basics, then the interesting stuff.",
      superpower: "Pick one or two — what you actually bring to the table.",
      team: "Two-time-collaborators outperform first-time pairs ~3:1 in pre-seed. Doesn't disqualify anyone — just useful colour.",
      pitch: "Strong one-liners punch above their weight in our process. Spend two extra minutes here.",
      whyNow: "The 'why now' question is what separates fund-grade from forever-startup.",
      risk: "The honest answer signals self-awareness — that's what we look for.",
      ask: "We can move within 14 days — assuming the basics check out.",
      helpFit: "This is a hint, not a vote. We decide the actual fit once we read your application.",
    },
    review: {
      title: "Look it over.",
      sub: "Last chance to edit anything. Add your pitch deck if you have one.",
      uploadLabel: "Pitch deck (file upload)",
      submit: "Submit application →",
    },
    confirm: {
      received: "Application received",
      thanks: (firstName: string) => `Thanks, ${firstName || "founder"}.`,
      bodyPre: "We've got your application for ",
      bodyMid: ". A confirmation has been sent to ",
      bodyEnd: ".",
      timeline: [
        { n: "Day 1–3", label: "Read", body: "We read every application. No deck templates, no bots scoring you." },
        { n: "Day 3–10", label: "Conversation", body: "If there's signal, we'll book a 30-min call. Camera optional." },
        { n: "Day 14", label: "Decision", body: "Yes / no / honest reason. If yes, paperwork starts the next morning." },
      ],
      whileYouWait: "While you wait — ",
      whileItems: [
        { title: "theblankcollar.com", body: "See the knowledge layer in action.", href: "https://www.theblankcollar.com" },
        { title: "blankcollar.ai", body: "Browse the agentic OS we'll set up for you.", href: "https://www.blankcollar.ai" },
        { title: "Portfolio", body: "Founders we've already helped.", href: "/#portfolio" },
      ],
      replyNote: " If anything urgent comes up, just reply to the confirmation email. It comes from a real human inbox.",
    },
  },
};

const de: typeof en = {
  common: {
    apply: "Bewerben",
    applyArrow: "Bewerben →",
    continue: "Weiter",
    back: "Zurück",
    edit: "Bearbeiten",
    saved: "Gespeichert",
    pressEnter: "Drücke",
    enterToContinue: "um weiterzugehen",
    optional: "optional",
    sending: "Wird gesendet…",
    submit: "Bewerbung absenden",
    backToSite: "← Zurück zur Seite",
  },
  header: {
    manifesto: "Manifest",
    stack: "Stack",
    tiers: "So arbeiten wir",
    toolkit: "Toolkit",
    process: "Prozess",
    portfolio: "Portfolio",
    terms: "Konditionen",
  },
  hero: {
    eyebrow: "Die blankcollar Familie · Pre-Seed",
    h1a: "KI hat verändert,",
    h1b: "was Gründer bauen.",
    h2: "Wir haben verändert, was VCs liefern.",
    sub1: "Wir sind der Pre-Seed-VC-Arm von blankcollar — gebaut für die KI-Ära, mit Sitz in der Schweiz. Bis zu ",
    subAmount: "CHF 50'000",
    sub2: " Kapital, das Wissen von ",
    sub3: " und ein voll konfiguriertes ",
    sub4: ".",
    primaryCta: "Jetzt bewerben",
    secondaryCta: "Manifest lesen",
    backedLabel: "Investiert in:",
  },
  marquee: [
    "Pre-Seed-Cheques bis CHF 50'000",
    "Entscheidung in 14 Tagen",
    "Wissen von theblankcollar.com",
    "Gratis, konfigurierter Zugang zu blankcollar.ai",
    "Pitch Deck, Data Room, Geschäftsmodell — gemeinsam gebaut",
    "Hands-on, nicht hands-off",
  ],
  stats: {
    cheque: "Cheque-Grösse",
    decision: "Entscheidungszeit",
    toolkit: "Toolkit-Module",
    agents: "Aktive Agents",
  },
  manifesto: {
    eyebrow: "01 — Manifest",
    h1: "Die meisten Pre-Seed-Fonds",
    h2: "überweisen Geld und verschwinden.",
    h3: "Wir machen das Gegenteil.",
    p1a: "Das grösste Problem für Gründer ist nicht, den Cheque zu bekommen. Es sind das Pitch Deck, der Data Room, das Geschäftsmodell, die ersten Hires, die Preisgestaltung — die Dinge, die First-Time-Gründer nicht alleine herausfinden sollten, aber immer müssen.",
    p2a: "blankcollar.vc schreibt den Cheque und gibt dir das Wissen von ",
    p2b: " und konfiguriert ",
    p2c: " — unser agentisches OS — für dein Unternehmen. Wir machen die Arbeit nicht für dich. Wir sorgen dafür, dass du es kannst.",
  },
  founders: {
    eyebrow: "02 — Hinter dem Fonds",
    h1: "Wir sind keine",
    h2: "Karriere-Investoren.",
    p1: "blankcollar.vc wird von Gründern geführt, die ihre eigenen Startups gebaut, skaliert und verkauft haben. Wir sassen in den Pitch-Reviews, verloren Term Sheets, stellten die falschen ersten drei Engineers ein — und fanden schliesslich heraus, was wirklich den Unterschied macht.",
    p2: "Jetzt investieren wir, was wir uns selbst gewünscht hätten: einen Cheque, die Playbooks für die schweren Sachen, und ein OS, das alles kodifiziert — damit du dein erstes Jahr nicht damit verbringst, neu zu lernen, was wir längst wissen.",
    milestones: [
      { stage: "Gebaut", body: "Unternehmen aus einem Laptop und einem One-Pager gestartet." },
      { stage: "Skaliert", body: "Die erste Stellenanzeige geschrieben, das erste SAFE, die erste Investoren-Mail." },
      { stage: "Verkauft", body: "Die Runde geschlossen, das Unternehmen verkauft, den Cap Table ausgezahlt." },
      { stage: "Jetzt", body: "Wir investieren, was wir uns am ersten Tag selbst gewünscht hätten." },
    ],
  },
  stack: {
    eyebrow: "03 — Der Stack",
    h1: "Eine Bewerbung.",
    h2: "Drei Ebenen Hebelwirkung.",
    sub: "Gebaut wie ein OS. Kapital ermöglicht die nächste Ebene. Wissen macht die Ebene darüber nutzbar. Agents lassen alles skalieren.",
    youAreHere: "● Du bist hier",
    together: "Zusammen = ein vollständiges Startup",
    layers: [
      { label: "L3", name: "Agentisches OS", site: "blankcollar.ai", voice: "bot", description: "Wir richten dein agentisches OS ein, damit das Wissen oben als Automation läuft, nicht als Ratschlag." },
      { label: "L2", name: "Wissen", site: "theblankcollar.com", voice: "human", description: "Praktische Hilfe bei Dingen, die First-Time-Gründer nicht alleine herausfinden sollten." },
      { label: "L1", name: "Kapital", site: "blankcollar.vc", voice: "human", description: "Bis zu CHF 50'000, Pre-Seed, gründerfreundliche Konditionen.", current: true },
    ],
  },
  tiers: {
    eyebrow: "04 — So arbeiten wir",
    h1: "Zwei Wege, wie wir arbeiten.",
    h2: "Wir wählen, was passt.",
    sub1: "Jeder Gründer, den wir unterstützen, bekommt das Wissen von theblankcollar.com und einen konfigurierten Zugang zu blankcollar.ai. Ob wir auch den Cheque schreiben — bis zu CHF 50'000 — hängt von deiner Phase ab. Wir entscheiden nach deiner Bewerbung, was passt.",
    cards: [
      {
        id: "access",
        name: "The Access",
        audience: "Für Gründer, die bereits Kapital haben",
        capital: "Wissen + OS",
        features: [
          "Voller Zugang zu den theblankcollar.com Playbooks",
          "Konfigurierter Zugang zu blankcollar.ai — deinem agentischen OS",
          "Pitch Deck, Data Room, Geschäftsmodell — gemeinsam gebaut",
          "Warme Vorstellungen für Seed / Series A, wenn du bereit bist",
        ],
      },
      {
        id: "full-stack",
        name: "The Full Stack",
        audience: "Für Gründer, die den Schub brauchen",
        capital: "Bis CHF 50'000 + alles aus The Access",
        features: [
          "Bis zu CHF 50'000 auf einem gründerfreundlichen SAFE",
          "Voller Zugang zu den theblankcollar.com Playbooks",
          "Konfigurierter Zugang zu blankcollar.ai — deinem agentischen OS",
          "Pitch Deck, Data Room, Geschäftsmodell — gemeinsam gebaut",
          "Warme Vorstellungen für Seed / Series A, wenn du bereit bist",
        ],
        emphasis: true,
      },
    ],
    ctaBody: "Nicht sicher, was passt? Genau dafür ist die Bewerbung da — sag uns, was du baust, und wir melden uns mit unserer Einschätzung.",
    ctaLink: "Sende deine Bewerbung",
  },
  toolkit: {
    eyebrow: "05 — Das First-Time-Gründer-Toolkit",
    h1: "Die schweren Sachen,",
    h2: "die du nicht allein lösen musst.",
    sub1: "Acht Module, die wir in den ersten Wochen mit dir bauen. Wir teilen, was wir gelernt haben, und verdrahten es dann in deine ",
    sub2: " Agents — damit es weiter wirkt.",
    items: [
      { label: "Pitch Deck", body: "Story-Bogen, Deck-Design, die sieben Slides, die jeder Fonds wirklich liest." },
      { label: "Data Room", body: "Cap Table, Verträge, KPIs, Hiring-Docs — sauber von Tag eins." },
      { label: "Geschäftsmodell", body: "Pricing, Unit Economics, woher die Marge wirklich kommt." },
      { label: "Cap Table & SAFEs", body: "Founder-Splits, Pool, Conversions — saubere Equity ab dem ersten Ticket." },
      { label: "Fundraising-Plan", body: "Zielliste, Reihenfolge, das richtige Narrativ pro Fonds." },
      { label: "Hiring-Playbook", body: "Stellenanzeigen, Comp-Benchmarks, woher die ersten 5 Hires kommen." },
      { label: "Customer Discovery", body: "Interview-Skript, was zu ignorieren ist, wann man aufhören soll zu reden." },
      { label: "Pricing & Packaging", body: "Tiers, Anchoring, die Pricing-Page, die konvertiert." },
    ],
  },
  network: {
    eyebrow: "06 — In der Praxis",
    h1: "Du im Zentrum.",
    h2: "Wissen rund um dich.",
    h3: "Agents im OS.",
    p: "Vom ersten Tag an rätst du nicht mehr. Wir teilen, was über zehn Bereiche hinweg funktioniert, die jeder Gründer irgendwann braucht — und konfigurieren deine Agents auf ",
    p2: ", damit das Wissen als Automation läuft.",
    knowledgeLabel: "Wissen",
    knowledgeBody: " — Pitch Deck, Data Room, Geschäftsmodell, Fundraising, Hiring, Sales, Pricing, Finance, Legal, Brand.",
    agentsLabel: "Agents",
    agentsBody: " — Research, Outreach, Ops, Reporting, Support. Konfiguriert auf deinen Stack.",
    legendKnowledge: "Wissen, das wir teilen (Mensch)",
    legendAgents: "Agents, die wir einrichten (Bot)",
    knowledgeNodes: ["Pitch Deck", "Data Room", "Geschäftsmodell", "Fundraising", "Hiring", "Sales", "Pricing", "Finance", "Legal", "Brand"],
    agentNodes: ["agent.research", "agent.outreach", "agent.ops", "agent.report", "agent.support"],
    centerLabel: "GRÜNDER",
    centerSub: "● DU",
  },
  process: {
    eyebrow: "07 — Prozess",
    h1: "Kein Deck. Keine warme Vorstellung.",
    h2: "Fünf Schritte. Zwei Wochen.",
    steps: [
      { n: "01", label: "Bewerben", body: "Schick uns einen Absatz und einen Link. Kein Deck nötig, keine warme Vorstellung.", detail: "~5 Min." },
      { n: "02", label: "Entscheidung", body: "Wir antworten in maximal 14 Tagen. Ja, nein, oder ein ehrlicher Grund warum.", detail: "≤ 14 Tage" },
      { n: "03", label: "Cheque überwiesen", body: "Bis zu CHF 50'000, gründerfreundliche Konditionen. SAFE oder Äquivalent.", detail: "≤ CHF 50'000" },
      { n: "04", label: "Wissenstransfer", body: "Wir setzen uns mit dir an die schweren Themen — Pitch Deck, Data Room, Geschäftsmodell, Hiring.", detail: "Ab Woche 1" },
      { n: "05", label: "OS konfiguriert", body: "Wir richten blankcollar.ai für dich ein. Deine Agents, dein Speicher, unser Wissen — kodifiziert.", detail: "Gratis, für immer" },
    ],
    stepLabel: "Schritt",
  },
  compare: {
    eyebrow: "08 — vs. klassisches Pre-Seed",
    h1: "Gleiches Geld.",
    h2: "Anderer Fonds.",
    sub: "Der Unterschied ist nicht die Cheque-Grösse. Es ist, was am Tag danach kommt.",
    headerFeature: "Aspekt",
    headerTrad: "Klassisches Pre-Seed",
    headerUs: "blankcollar.vc",
    rows: [
      { feature: "Cheque-Grösse", trad: "CHF 50'000 – 250'000 (oft verwässert)", us: "Bis CHF 50'000, gründerfreundlich" },
      { feature: "Entscheidungszeit", trad: "Wochen voller Meetings", us: "Maximal 14 Tage" },
      { feature: "Nach der Überweisung", trad: "Quartalsweise Check-ins", us: "Praktische Hilfe bei den schweren Sachen" },
      { feature: "Pitch Deck & Data Room", trad: "„Schickt es uns, wenn ihr soweit seid“", us: "In Woche eins gemeinsam gebaut" },
      { feature: "Geschäftsmodell-Hilfe", trad: "Vorstellungen zu Beratern", us: "Pricing, Unit Economics, Moats" },
      { feature: "KI / Automation", trad: "„Habt ihr ChatGPT mal probiert?“", us: "Wir richten blankcollar.ai für dich ein" },
      { feature: "Hiring-Hilfe", trad: "Vorstellungen zu Recruitern", us: "Playbooks, Stellenanzeigen, Comp-Benchmarks" },
      { feature: "Board-Beteiligung", trad: "Beobachtersitz", us: "Keine in dieser Phase" },
      { feature: "Netzwerk", trad: "LP-Vorstellungen", us: "Wissen + Agents + Portfolio" },
    ],
    inlineTradLabel: "Klassisch ·",
  },
  portfolio: {
    eyebrow: "09 — Portfolio",
    h1: "Gründer, die wir geholfen haben",
    h2: "von Anfang bis Ende zu skalieren.",
    sub1: "Fünf Schweizer / EU-Unternehmen, gebaut auf demselben Playbook: Kapital, Wissen und ein agentisches OS — alles ab Tag eins eingebaut. ",
    sub2: "Ein Exit bisher. Vier weiter im Steigen.",
    statusActive: "Aktiv",
    statusExited: "Exited",
    companies: [
      { name: "Numarics", domain: "numarics.com", url: "https://numarics.com", category: "Fintech / Buchhaltung", body: "AI-natives Accounting für KMU und Treuhand. Gebaut, skaliert, verkauft — treibt jetzt seinen Nachfolger Money Key an.", origin: "CH", status: "exited" as const },
      { name: "Cybee.ai", domain: "cybee.ai", url: "https://cybee.ai", category: "Cybersecurity", body: "Cybersecurity & Compliance für KMU. SOC 2, GDPR, ISO 27001 — automatisiert, in Klartext.", origin: "CH", status: "active" as const },
      { name: "iQTax", domain: "iqtax.ch", url: "https://iqtax.ch", category: "AI Tax", body: "Die KI-Plattform für Schweizer Steuererklärungen. Hochladen, einreichen, fertig — in Minuten, nicht Stunden.", origin: "CH", status: "active" as const },
      { name: "Alletta", domain: "alletta.ch", url: "https://alletta.ch", category: "InsurTech", body: "Die erste vollständig digitale, KI-gestützte Plattform für Kranken- und Rechtsschutzversicherungen in der Schweiz.", origin: "CH", status: "active" as const },
      { name: "Visorway", domain: "visorway.ai", url: "https://visorway.ai", category: "AI Consulting", body: "AI-natives Consulting. Ein KI-Berater vor vollwertigen IT- und ESG-Beratungs-Engines.", origin: "EU", status: "active" as const },
    ],
  },
  netSection: {
    eyebrow: "10 — FYI",
    h1: "Wir kennen viele",
    h2: "Investoren.",
    p1: "Kein Sales-Pitch — nur nützlich zu wissen. Nach Jahren des Aufbauens und Verkaufens unserer eigenen Startups haben wir die Kontakte behalten: Seed-Fonds, Series A, Family Offices, die richtigen Angels.",
    p2: "Wir co-investieren nicht und verkaufen kein „Netzwerk“. Aber wenn du bereit für die nächste Runde bist, machen wir warme Vorstellungen zu den richtigen Leuten — direkt, nicht über ein Portal.",
    stats: [
      { n: "Direkt", label: "Beziehungen, kein Portal" },
      { n: "Pre-Seed → B", label: "Über alle Folgerunden hinweg" },
      { n: "Nur warm", label: "Wir machen die Vorstellung, nicht du" },
    ],
  },
  terms: {
    eyebrow: "11 — Konditionen",
    h1: "Was du bekommst,",
    h2: "auf den Punkt.",
    rows: [
      { k: "Cheque", v: "Bis CHF 50'000" },
      { k: "Phase", v: "Pre-Seed / Tag 0" },
      { k: "Geografie", v: "Global, remote-first" },
      { k: "Tempo", v: "Entscheidung in 14 Tagen" },
      { k: "Konditionen", v: "Gründerfreundliche Bedingungen" },
      { k: "Plus", v: "Wissen + Agentic OS" },
    ],
  },
  cta: {
    badge: "Wir prüfen aktuell Bewerbungen",
    h1a: "Baust",
    h1b: "du was?",
    h2a: "Wir helfen",
    h2b: "gerne.",
    sub: "Ein Absatz, ein Link. Wenn es passt, gehen wir schnell — Kapital, Wissen und das OS, bereit zum Einsatz.",
    primary: "Bewerbung starten",
    secondary: "Portfolio ansehen",
  },
  footer: {
    tagline: "Der Pre-Seed-Fonds der blankcollar Familie. Kapital, Wissen und ein agentisches OS — in einem Cheque.",
    family: "Familie",
    page: "Seite",
    contact: "Kontakt",
    pageItems: ["Manifest", "Stack", "Toolkit", "Portfolio", "Konditionen"],
    motto: "Arbeit ist für Bots. Leben ist für Menschen.",
  },
  apply: {
    eyebrow: "Bewerbung",
    title: "Sag uns, was du baust.",
    sub: "~7 Minuten. Speichert automatisch. Wir antworten in maximal 14 Tagen — ja, nein, oder ein ehrlicher Grund.",
    sectionsLabels: { you: "Du", team: "Team", company: "Unternehmen", vision: "Vision", ask: "Bedarf", materials: "Material", review: "Überprüfen" },
    stepOf: "Schritt",
    of: "von",
    feedback: {
      basics: "Kurze Basics, dann kommt das Spannende.",
      superpower: "Wähle eine oder zwei — was du wirklich mitbringst.",
      team: "Teams, die schon zusammen gearbeitet haben, performen ~3:1 besser im Pre-Seed. Disqualifiziert niemanden — nur nützliche Farbe.",
      pitch: "Starke One-Liner schlagen oft schwerer als ihr Gewicht. Investiere zwei Minuten extra hier.",
      whyNow: "Die Frage „Warum jetzt“ trennt fund-grade von forever-startup.",
      risk: "Die ehrliche Antwort signalisiert Selbstwahrnehmung — genau das suchen wir.",
      ask: "Wir können in 14 Tagen entscheiden — wenn die Basics passen.",
      helpFit: "Das ist ein Hinweis, keine Wahl. Wir entscheiden den passenden Tier nach deiner Bewerbung.",
    },
    review: {
      title: "Schau drüber.",
      sub: "Letzte Chance, etwas zu ändern. Lade dein Pitch Deck hoch, falls du eines hast.",
      uploadLabel: "Pitch Deck (Datei-Upload)",
      submit: "Bewerbung absenden →",
    },
    confirm: {
      received: "Bewerbung erhalten",
      thanks: (firstName: string) => `Danke, ${firstName || "Gründer"}.`,
      bodyPre: "Wir haben deine Bewerbung für ",
      bodyMid: " erhalten. Eine Bestätigung wurde an ",
      bodyEnd: " gesendet.",
      timeline: [
        { n: "Tag 1–3", label: "Lesen", body: "Wir lesen jede Bewerbung. Keine Deck-Vorlagen, keine Bots, die dich bewerten." },
        { n: "Tag 3–10", label: "Gespräch", body: "Wenn es Signal gibt, buchen wir ein 30-Minuten-Call. Kamera optional." },
        { n: "Tag 14", label: "Entscheidung", body: "Ja / nein / ehrlicher Grund. Wenn ja, starten wir am nächsten Morgen mit dem Papierkram." },
      ],
      whileYouWait: "Solange du wartest — ",
      whileItems: [
        { title: "theblankcollar.com", body: "Sieh die Wissens-Ebene in Aktion.", href: "https://www.theblankcollar.com" },
        { title: "blankcollar.ai", body: "Schau dir das agentische OS an, das wir für dich einrichten.", href: "https://www.blankcollar.ai" },
        { title: "Portfolio", body: "Gründer, denen wir bereits geholfen haben.", href: "/de#portfolio" },
      ],
      replyNote: " Wenn etwas Dringendes auftaucht, antworte einfach auf die Bestätigungsmail. Sie kommt aus einem echten Posteingang.",
    },
  },
};

export type Dict = typeof en;

export const dict: Record<Lang, Dict> = { en, de };
