// Bilingual content dictionary.
// German uses Swiss writing rules: no ß (use ss), apostrophe thousands separator
// (CHF 50'000), informal "du" voice throughout. Tech terms stay English where
// they're standard in Swiss/DE startup contexts (Pre-Seed, Pitch Deck, Cap
// Table, SAFE, Agentic OS, etc.).
//
// POSITIONING (2026-06-13): blankcollar.ventures is NOT a fund that writes cheques.
// It is the operating partner that makes founders fundable — knowledge
// (theblankcollar.com), upskilling (blankcollar.university), AI operations
// (blankcollar.ai), and warm access to the VCs we work with (they write the
// cheques, not us). No CHF 50K / SAFE / "capital wired" language anywhere.

import type { Lang } from "./lang";

const en = {
  common: {
    apply: "Apply",
    applyArrow: "Apply →",
    continue: "Continue",
    back: "Back",
    edit: "Edit",
    saved: "Saved",
    pressEnter: "Press",
    enterToContinue: "to continue",
    optional: "optional",
    sending: "Sending…",
    submit: "Submit application",
    backToSite: "← Back to site",
    skipToContent: "Skip to content",
    progressLabel: "Application progress",
  },
  header: {
    manifesto: "Manifesto",
    stack: "Stack",
    tiers: "Tiers",
    toolkit: "Toolkit",
    process: "Process",
    portfolio: "Portfolio",
    terms: "Terms",
  },
  hero: {
    eyebrow: "The blankcollar family · Ventures",
    h1a: "AI changed what",
    h1b: "founders build.",
    h2: "We change how they get funded.",
    sub1: "We're the ventures arm of blankcollar — built for the AI era, based in Switzerland. We don't write the cheque; we make you fundable. The knowledge from ",
    sub2: ", a configured agentic OS on ",
    sub3: ", the courses on ",
    sub4: ", and warm intros to the VCs we work with.",
    primaryCta: "Apply to work with us",
    secondaryCta: "Read the manifesto",
    backedLabel: "Worked with:",
  },
  marquee: [
    "We don't write the cheque — we make you fundable",
    "Knowledge from theblankcollar.com",
    "AI operations on blankcollar.ai",
    "Upskilling on blankcollar.university",
    "Warm intros to the VCs we work with",
    "Decisions in 14 days",
  ],
  stats: {
    domains: "Knowledge domains",
    decision: "Decision time",
    toolkit: "Toolkit modules",
    agents: "Always-on agents",
  },
  manifesto: {
    eyebrow: "01 — Manifesto",
    h1: "Most funds wire money",
    h2: "and disappear.",
    h3: "We're not a fund.",
    p1a: "The biggest problem founders face isn't getting the cheque. It's becoming fundable — the pitch deck, the data room, the business model, the first hires, the pricing, the story a real VC will back. The things first-time founders shouldn't have to figure out alone, but always do.",
    p2a: "blankcollar.ventures gives you the knowledge from ",
    p2b: ", the courses from ",
    p2c: ", and a configured agentic OS on ",
    p2d: " — then opens the doors to the VCs we work with. We don't write the cheque. We make sure you can earn one.",
  },
  founders: {
    eyebrow: "02 — Behind the firm",
    h1: "We're not",
    h2: "career investors.",
    p1: "blankcollar.ventures is run by founders who built, scaled, and exited their own startups. We sat through the pitch reviews, lost the term sheets, hired the wrong first three engineers, and finally figured out what actually moves the needle.",
    p2: "Now we give what we wish we'd had: the playbooks for the hard things, the courses to level up fast, an OS that codifies it all, and a warm intro to the right fund when you're ready — so you don't spend year one re-learning what we already know.",
    milestones: [
      { stage: "Built", body: "Started companies from a spare laptop and a one-page deck." },
      { stage: "Scaled", body: "Wrote the first JD, the first SAFE, the first investor email." },
      { stage: "Exited", body: "Closed the round, sold the company, paid out the cap table." },
      { stage: "Now", body: "Giving founders what we wish we'd had on day zero." },
    ],
  },
  stack: {
    eyebrow: "03 — The Stack",
    h1: "One application.",
    h2: "Four kinds of leverage.",
    sub: "Built like an OS. Knowledge makes you credible. Skills make you fast. Agents make it scale. Access gets you funded.",
    youAreHere: "● You are here",
    together: "Together = a fundable startup",
    layers: [
      { label: "01", name: "Knowledge", site: "theblankcollar.com", voice: "human", description: "The thinking and playbooks for the things first-time founders shouldn't face alone." },
      { label: "02", name: "Upskilling", site: "blankcollar.university", voice: "human", description: "Courses that level you and your team up on AI-era operating — fast." },
      { label: "03", name: "AI Operations", site: "blankcollar.ai", voice: "bot", description: "We configure your agentic OS so the knowledge runs as automation, not advice." },
      { label: "04", name: "Capital Access", site: "blankcollar.ventures", voice: "human", description: "Warm intros to the VCs we work with — directly, when you're ready to raise.", current: true },
    ],
  },
  tiers: {
    eyebrow: "04 — How we work",
    h1: "Two ways we work.",
    h2: "We pick the fit.",
    sub1: "Every founder we work with gets the knowledge from theblankcollar.com, the courses on blankcollar.university, and a configured seat on blankcollar.ai. How hands-on we go on the raise — and which VCs we open — depends on your stage. We decide the fit once we've read your application.",
    cards: [
      {
        id: "access",
        name: "The Essentials",
        audience: "For founders finding their feet",
        capital: "Knowledge + OS",
        features: [
          "Full access to theblankcollar.com playbooks",
          "Configured seat on blankcollar.ai — your agentic OS",
          "Courses on blankcollar.university",
          "Pitch deck, data room, business model — co-built",
        ],
      },
      {
        id: "full-stack",
        name: "The Full Stack",
        audience: "For founders ready to raise",
        capital: "Everything + VC access",
        features: [
          "Everything in The Essentials",
          "We run the raise with you, hands-on",
          "Warm intros to the VCs we work with",
          "Follow-on guidance through seed / Series A",
        ],
        emphasis: true,
      },
    ],
    ctaBody: "Not sure which fits? That's the point of the application — tell us what you're building, and we'll come back with our read.",
    ctaLink: "Send us your application",
  },
  toolkit: {
    eyebrow: "05 — The First-Time Founder Toolkit",
    h1: "The hard things you",
    h2: "don't have to figure out alone.",
    sub1: "Eight modules we co-build with you in the first weeks. We share what we've learned, teach it on ",
    sub2: ", then wire it into your ",
    sub3: " agents so it keeps compounding.",
    items: [
      { label: "Pitch deck", body: "Story arc, deck design, the seven slides every fund actually reads." },
      { label: "Data room", body: "Cap table, contracts, KPIs, hiring docs — clean from day one." },
      { label: "Business model", body: "Pricing, unit economics, where margin actually comes from." },
      { label: "Cap table & SAFEs", body: "Founder splits, pool, conversions — clean equity from the first ticket." },
      { label: "Fundraising plan", body: "Target list, sequencing, the right narrative for each fund." },
      { label: "Hiring playbook", body: "JDs, comp benchmarks, where to source the first 5 hires." },
      { label: "Customer discovery", body: "Interview script, what to ignore, when to stop talking." },
      { label: "Pricing & packaging", body: "Tiers, anchoring, the pricing page that converts." },
    ],
  },
  network: {
    eyebrow: "06 — In practice",
    h1: "You at the centre.",
    h2: "Knowledge around you.",
    h3: "Agents inside the OS.",
    p: "Day one, you're no longer guessing. We share what works across ten domains every founder eventually needs, then we configure your agents on ",
    p2: " so the knowledge runs as automation.",
    knowledgeLabel: "Knowledge",
    knowledgeBody: " — pitch deck, data room, business model, fundraising, hiring, sales, pricing, finance, legal, brand.",
    agentsLabel: "Agents",
    agentsBody: " — research, outreach, ops, reporting, support. Configured for your stack.",
    legendKnowledge: "Knowledge we share (human)",
    legendAgents: "Agents we set up (bot)",
    knowledgeNodes: ["Pitch deck", "Data room", "Business model", "Fundraising", "Hiring", "Sales", "Pricing", "Finance", "Legal", "Brand"],
    agentNodes: ["agent.research", "agent.outreach", "agent.ops", "agent.report", "agent.support"],
    centerLabel: "FOUNDER",
    centerSub: "● YOU",
  },
  process: {
    eyebrow: "07 — Process",
    h1: "No deck. No warm intro.",
    h2: "Five steps. Two weeks.",
    steps: [
      { n: "01", label: "Apply", body: "Send us a paragraph and a link. No deck required, no warm intro needed.", detail: "~5 min" },
      { n: "02", label: "Decision", body: "We respond in 14 days max. Yes, no, or honest reason why.", detail: "≤ 14 days" },
      { n: "03", label: "Knowledge & courses", body: "The thinking from theblankcollar.com and the courses from blankcollar.university — yours from week one.", detail: "Week 1" },
      { n: "04", label: "OS configured", body: "We set up blankcollar.ai for you. Your agents, your memory, our knowledge — codified.", detail: "Free, forever" },
      { n: "05", label: "Warm intros", body: "When you're fundable, we open the doors to the VCs we work with — directly, not via a portal.", detail: "When ready" },
    ],
    stepLabel: "Step",
  },
  compare: {
    eyebrow: "08 — vs Traditional pre-seed",
    h1: "Not a fund.",
    h2: "A way in.",
    sub: "Most pre-seed money comes with a quarterly check-in. We come with the knowledge, the AI setup, the upskilling — and the intro that gets you the money in the first place.",
    headerFeature: "Feature",
    headerTrad: "Traditional pre-seed",
    headerUs: "blankcollar.ventures",
    rows: [
      { feature: "Capital", trad: "Their cheque, diluting you early", us: "Warm intros to the VCs we work with" },
      { feature: "Decision time", trad: "Weeks of meetings", us: "14 days, max" },
      { feature: "After yes", trad: "Quarterly check-ins", us: "Hands-on until you're fundable" },
      { feature: "Pitch deck & data room", trad: "“Send us when ready”", us: "Co-built with you, week one" },
      { feature: "Business model help", trad: "Intros to advisors", us: "Pricing, unit economics, moats" },
      { feature: "AI / automation", trad: "“Have you tried ChatGPT?”", us: "We set up blankcollar.ai for you" },
      { feature: "Upskilling", trad: "You figure it out", us: "Courses on blankcollar.university" },
      { feature: "Hiring help", trad: "Intros to recruiters", us: "Playbooks, JDs, comp benchmarks" },
      { feature: "Network", trad: "LP intros", us: "Direct intros to the VCs we work with" },
    ],
    inlineTradLabel: "Traditional ·",
  },
  portfolio: {
    eyebrow: "09 — Portfolio",
    h1: "Founders we've helped",
    h2: "scale from start to finish.",
    sub1: "Five Swiss / EU companies built on the same playbook: knowledge, AI operations, upskilling, and the intros that mattered — wired in from day one. ",
    sub2: "One exit so far. Four still climbing.",
    statusActive: "Active",
    statusExited: "Exited",
    companies: [
      { name: "Numarics", domain: "numarics.com", url: "https://numarics.com", category: "Fintech / Accounting", body: "AI-native accounting for SMEs and fiduciary partners. Built, scaled, exited — now powering its successor, Money Key.", origin: "CH", status: "exited" as const },
      { name: "Cybee.ai", domain: "cybee.ai", url: "https://cybee.ai", category: "Cybersecurity", body: "Cybersecurity & compliance for SMBs. SOC 2, GDPR, ISO 27001 — automated, in plain language.", origin: "CH", status: "active" as const },
      { name: "iQTax", domain: "iqtax.ch", url: "https://iqtax.ch", category: "AI Tax", body: "The AI platform for Swiss tax declarations. Upload, file, done — in minutes, not hours.", origin: "CH", status: "active" as const },
      { name: "Alletta", domain: "alletta.ch", url: "https://alletta.ch", category: "InsurTech", body: "First fully digital, AI-powered health & legal insurance platform in Switzerland.", origin: "CH", status: "active" as const },
      { name: "Visorway", domain: "visorway.ai", url: "https://visorway.ai", category: "AI Consulting", body: "AI-native consulting. One AI advisor in front of full IT and ESG advisory engines.", origin: "EU", status: "active" as const },
    ],
  },
  netSection: {
    eyebrow: "10 — Access",
    h1: "We know a lot",
    h2: "of investors.",
    p1: "Not a sales pitch — it's the point. After years of building and exiting our own startups, we've kept the contacts: seed funds, Series A, family offices, the right angels.",
    p2: "We don't write the cheque ourselves. But when you're fundable, we make warm intros to the right ones — directly, not via a portal. That's how our founders raise.",
    stats: [
      { n: "Direct", label: "Relationships, not a portal" },
      { n: "Pre-seed → B", label: "Across follow-on stages" },
      { n: "Warm only", label: "We make the intro, not you" },
    ],
  },
  terms: {
    eyebrow: "11 — Terms",
    h1: "What you get,",
    h2: "in plain English.",
    rows: [
      { k: "Our cheque", v: "We don't write one" },
      { k: "What you get", v: "Knowledge, AI ops, upskilling" },
      { k: "Capital", v: "Warm intros to partner VCs" },
      { k: "Stage", v: "Pre-seed / Day 0" },
      { k: "Geography", v: "Global, remote-first" },
      { k: "Speed", v: "Decisions in 14 days" },
    ],
  },
  cta: {
    badge: "Now reviewing applications",
    h1a: "Building",
    h1b: "something?",
    h2a: "We'd love to",
    h2b: "help.",
    sub: "One paragraph, one link. If it's a fit, we move fast — knowledge, AI, upskilling, and the intro, ready to go.",
    primary: "Start your application",
    secondary: "See the portfolio",
  },
  footer: {
    tagline: "The ventures arm of the blankcollar family. Knowledge, AI operations, upskilling, and access to the VCs we work with.",
    family: "Family",
    page: "Page",
    contact: "Contact",
    pageItems: ["Manifesto", "Stack", "Toolkit", "Portfolio", "Terms"],
    motto: "Work is for bots. Life is for humans.",
  },
  apply: {
    eyebrow: "Application",
    title: "Tell us what you're building.",
    sub: "~7 minutes. Auto-saves as you go. We respond in 14 days max — yes, no, or an honest reason why.",
    sectionsLabels: { you: "You", team: "Team", company: "Company", vision: "Vision", ask: "Ask", materials: "Materials", review: "Review" },
    stepOf: "Step",
    of: "of",
    feedback: {
      basics: "Quick basics, then the interesting stuff.",
      superpower: "Pick one or two — what you actually bring to the table.",
      team: "Two-time-collaborators outperform first-time pairs ~3:1 in pre-seed. Doesn't disqualify anyone — just useful colour.",
      pitch: "Strong one-liners punch above their weight in our process. Spend two extra minutes here.",
      whyNow: "The 'why now' question is what separates fund-grade from forever-startup.",
      risk: "The honest answer signals self-awareness — that's what we look for.",
      ask: "We can move within 14 days — assuming the basics check out.",
      helpFit: "This is a hint, not a vote. We decide the actual fit once we read your application.",
    },
    review: {
      title: "Look it over.",
      sub: "Last chance to edit anything. Add your pitch deck if you have one.",
      uploadLabel: "Pitch deck (file upload)",
      submit: "Submit application →",
    },
    confirm: {
      received: "Application received",
      thanks: (firstName: string) => `Thanks, ${firstName || "founder"}.`,
      bodyPre: "We've got your application for ",
      bodyMid: ". A confirmation has been sent to ",
      bodyEnd: ".",
      timeline: [
        { n: "Day 1–3", label: "Read", body: "We read every application. No deck templates, no bots scoring you." },
        { n: "Day 3–10", label: "Conversation", body: "If there's signal, we'll book a 30-min call. Camera optional." },
        { n: "Day 14", label: "Decision", body: "Yes / no / honest reason. If yes, we start the next morning." },
      ],
      whileYouWait: "While you wait — ",
      whileItems: [
        { title: "theblankcollar.com", body: "See the knowledge layer in action.", href: "https://www.theblankcollar.com" },
        { title: "blankcollar.ai", body: "Browse the agentic OS we'll set up for you.", href: "https://www.blankcollar.ai" },
        { title: "blankcollar.university", body: "The courses we'll point you to.", href: "https://www.blankcollar.university" },
        { title: "Portfolio", body: "Founders we've already helped.", href: "/#portfolio" },
      ],
      replyNote: " If anything urgent comes up, just reply to the confirmation email. It comes from a real human inbox.",
    },
    steps: {
      you1: "Tell us who you are.",
      you2: "What's your superpower?",
      team: "Who's building this with you?",
      company: "The company.",
      stage: "Where are you on the curve?",
      sectorPitch: "Sector and the elevator pitch.",
      problem: "The problem you're solving.",
      solution: "What you're building, and why now.",
      whyNow: "Why now?",
      traction: "Customer conversations + traction.",
      risk: "What's your biggest risk right now?",
      ask: "The raise, and what it'll do.",
      helpFit: "What kind of help fits you?",
      materials: "Show us what you've got.",
    },
    fields: {
      yourName: { label: "Your name", placeholder: "Jane Doe" },
      email: { label: "Email", hint: "We'll use this for everything from here.", placeholder: "jane@yourstartup.com" },
      yourRole: { label: "Your role", placeholder: "CEO, CTO, Founder…" },
      location: { label: "Where based", hint: "City, country.", placeholder: "Zurich, CH" },
      linkedin: { label: "LinkedIn", placeholder: "https://linkedin.com/in/…" },
      workedTogether: { label: "How long have you worked together?" },
      teamDescription: { label: "Tell us about the team", hint: "Co-founders, key roles, who's full-time. One line each.", placeholder: "e.g.\nJane — CEO, ex-Stripe (FT)\nMarc — CTO, ex-Google (FT)\nWe're hiring a designer." },
      companyName: { label: "Company name", placeholder: "Stripe, Linear, …" },
      companyWebsite: { label: "Website", placeholder: "https://yourstartup.com" },
      sector: { label: "Sector" },
      oneLiner: { label: "One-line elevator pitch", hint: "If a stranger had to repeat it back to a friend, what would they say?", placeholder: '"Stripe for cross-border payroll in Africa."' },
      problem: { label: "The problem", hint: "In plain English. What's broken, and why hasn't it been fixed yet?" },
      customer: { label: "Who has this problem", hint: "Be specific about the customer.", placeholder: "e.g. 'CFOs at Series A SaaS companies in Europe with 20–80 employees'" },
      solution: { label: "Your solution", hint: "What are you building, in simple terms?" },
      differentiator: { label: "What's different", hint: "Why won't the obvious incumbent crush you?" },
      whyNow: { label: "Why is now the right moment to build this?", hint: "Tech shift, regulation, behaviour change, AI inflection — what's the catalyst?" },
      interviews: { label: "How many customer conversations have you had?", hint: "Zero is a fine answer — we just want the truth." },
      traction: { label: "Any traction so far", hint: "Revenue, signups, design partners, LOIs, waitlist — anything real." },
      raisingAmount: { label: "How much are you raising in this round", hint: "The round you're planning to raise.", placeholder: "e.g. CHF 250'000" },
      useOfFunds: { label: "What will the money do", hint: "Top 3 line items." },
      helpFit: { label: "Your read on what fits" },
      whyUs: { label: "Why blankcollar specifically", hint: "No wrong answer. Just be honest." },
      pitchDeckLink: { label: "Pitch deck link", hint: "Notion, Pitch, Google Slides, Loom — whatever you've got." },
      productLink: { label: "Product / demo link" },
      somethingElse: { label: "Anything else we should know" },
    },
    cards: {
      stage: {
        "pre-incorporation": { label: "Pre-incorporation", description: "Just an idea, maybe a prototype." },
        incorporated: { label: "Incorporated, pre-revenue", description: "Company exists, building toward first dollar." },
        "first-revenue": { label: "First revenue", description: "Real customers, real (small) money." },
        scaling: { label: "Scaling", description: "Repeatable revenue, hiring, picking up speed." },
      },
      worked: {
        "first-time": { label: "First time", description: "We just teamed up." },
        "less-than-6m": { label: "< 6 months", description: "Early days together." },
        "6m-to-2y": { label: "6 months – 2 years", description: "Tested under fire." },
        "over-2y": { label: "2+ years", description: "We've been through it." },
      },
      sector: {
        "ai-ml": "AI / ML",
        fintech: "Fintech",
        healthtech: "Healthtech",
        climate: "Climate",
        devtools: "Dev Tools",
        consumer: "Consumer",
        "b2b-saas": "B2B SaaS",
        other: "Other",
      },
      superpower: {
        story: { label: "Storytelling", description: "I sell the vision. People follow." },
        tech: { label: "Engineering", description: "I ship the product." },
        sales: { label: "Sales & GTM", description: "I close. I run the playbook." },
        ops: { label: "Operations", description: "I make things run, on time." },
        vision: { label: "Vision & Strategy", description: "I see two moves ahead." },
        network: { label: "Network", description: "I open doors others can't." },
      },
      interview: {
        none: { label: "Haven't started", description: "We're going on instinct (so far)." },
        "1-10": { label: "1 – 10", description: "Early signal, early conviction." },
        "10-50": { label: "10 – 50", description: "Real pattern recognition." },
        "50-plus": { label: "50+", description: "Deep customer obsession." },
      },
      risk: {
        demand: { label: "Customers won't buy", description: "Pull risk." },
        build: { label: "Building it is hard", description: "Tech / execution risk." },
        funding: { label: "Out of money first", description: "Runway risk." },
        team: { label: "Team / hiring", description: "People risk." },
        other: { label: "Something else", description: "Tell us in a sec." },
      },
      helpFit: {
        access: { label: "We need the lift", description: "We need the knowledge, the courses, and the agentic OS." },
        "full-stack": { label: "We're ready to raise", description: "We need all of it — and warm intros to the right VCs." },
      },
    },
    validations: {
      name: "Tell us your name",
      email: "Email looks off",
      role: "Add your role",
      location: "Where are you based?",
      superpower: "Pick at least one",
      workedTogether: "Pick one",
      teamDescription: "Tell us about the team",
      companyName: "Company name",
      stage: "Pick a stage",
      sector: "Pick a sector",
      oneLiner: "Give us the one-liner",
      problem: "Describe the problem",
      customer: "Who has this problem?",
      solution: "What are you building?",
      differentiator: "What's different?",
      whyNow: "Tell us why now",
      interviews: "Pick the closest range",
      risk: "Pick the closest",
      raisingAmount: "Raise amount",
      useOfFunds: "Use of funds",
      helpFit: "Tell us what fits",
      whyUs: "Tell us why",
    },
  },
};

const de: typeof en = {
  common: {
    apply: "Bewerben",
    applyArrow: "Bewerben →",
    continue: "Weiter",
    back: "Zurück",
    edit: "Bearbeiten",
    saved: "Gespeichert",
    pressEnter: "Drücke",
    enterToContinue: "um weiterzugehen",
    optional: "optional",
    sending: "Wird gesendet…",
    submit: "Bewerbung absenden",
    backToSite: "← Zurück zur Seite",
    skipToContent: "Zum Inhalt springen",
    progressLabel: "Fortschritt der Bewerbung",
  },
  header: {
    manifesto: "Manifest",
    stack: "Stack",
    tiers: "So arbeiten wir",
    toolkit: "Toolkit",
    process: "Prozess",
    portfolio: "Portfolio",
    terms: "Konditionen",
  },
  hero: {
    eyebrow: "Die blankcollar Familie · Ventures",
    h1a: "KI hat verändert,",
    h1b: "was Gründer bauen.",
    h2: "Wir verändern, wie sie finanziert werden.",
    sub1: "Wir sind der Ventures-Arm von blankcollar — gebaut für die KI-Ära, mit Sitz in der Schweiz. Wir schreiben den Cheque nicht; wir machen dich fundable. Das Wissen von ",
    sub2: ", ein konfiguriertes agentisches OS auf ",
    sub3: ", die Kurse auf ",
    sub4: " und warme Intros zu den VCs, mit denen wir arbeiten.",
    primaryCta: "Mit uns arbeiten",
    secondaryCta: "Manifest lesen",
    backedLabel: "Gearbeitet mit:",
  },
  marquee: [
    "Wir schreiben den Cheque nicht — wir machen dich fundable",
    "Wissen von theblankcollar.com",
    "AI-Operations auf blankcollar.ai",
    "Upskilling auf blankcollar.university",
    "Warme Intros zu den VCs, mit denen wir arbeiten",
    "Entscheidung in 14 Tagen",
  ],
  stats: {
    domains: "Wissensbereiche",
    decision: "Entscheidungszeit",
    toolkit: "Toolkit-Module",
    agents: "Aktive Agents",
  },
  manifesto: {
    eyebrow: "01 — Manifest",
    h1: "Die meisten Fonds überweisen Geld",
    h2: "und verschwinden.",
    h3: "Wir sind kein Fonds.",
    p1a: "Das grösste Problem für Gründer ist nicht, den Cheque zu bekommen. Es ist, fundable zu werden — das Pitch Deck, der Data Room, das Geschäftsmodell, die ersten Hires, die Preisgestaltung, die Story, die ein echter VC backt. Die Dinge, die First-Time-Gründer nicht alleine herausfinden sollten, aber immer müssen.",
    p2a: "blankcollar.ventures gibt dir das Wissen von ",
    p2b: ", die Kurse von ",
    p2c: " und ein konfiguriertes agentisches OS auf ",
    p2d: " — und öffnet dann die Türen zu den VCs, mit denen wir arbeiten. Wir schreiben den Cheque nicht. Wir sorgen dafür, dass du dir einen verdienen kannst.",
  },
  founders: {
    eyebrow: "02 — Hinter der Firma",
    h1: "Wir sind keine",
    h2: "Karriere-Investoren.",
    p1: "blankcollar.ventures wird von Gründern geführt, die ihre eigenen Startups gebaut, skaliert und verkauft haben. Wir sassen in den Pitch-Reviews, verloren Term Sheets, stellten die falschen ersten drei Engineers ein — und fanden schliesslich heraus, was wirklich den Unterschied macht.",
    p2: "Jetzt geben wir, was wir uns selbst gewünscht hätten: die Playbooks für die schweren Sachen, die Kurse zum schnellen Aufleveln, ein OS, das alles kodifiziert, und eine warme Vorstellung zum richtigen Fonds, wenn du bereit bist — damit du dein erstes Jahr nicht damit verbringst, neu zu lernen, was wir längst wissen.",
    milestones: [
      { stage: "Gebaut", body: "Unternehmen aus einem Laptop und einem One-Pager gestartet." },
      { stage: "Skaliert", body: "Die erste Stellenanzeige geschrieben, das erste SAFE, die erste Investoren-Mail." },
      { stage: "Verkauft", body: "Die Runde geschlossen, das Unternehmen verkauft, den Cap Table ausgezahlt." },
      { stage: "Jetzt", body: "Wir geben Gründern, was wir uns am ersten Tag selbst gewünscht hätten." },
    ],
  },
  stack: {
    eyebrow: "03 — Der Stack",
    h1: "Eine Bewerbung.",
    h2: "Vier Arten von Hebel.",
    sub: "Gebaut wie ein OS. Wissen macht dich glaubwürdig. Skills machen dich schnell. Agents skalieren alles. Zugang bringt die Finanzierung.",
    youAreHere: "● Du bist hier",
    together: "Zusammen = ein fundable Startup",
    layers: [
      { label: "01", name: "Wissen", site: "theblankcollar.com", voice: "human", description: "Das Denken und die Playbooks für die Dinge, die First-Time-Gründer nicht allein angehen sollten." },
      { label: "02", name: "Upskilling", site: "blankcollar.university", voice: "human", description: "Kurse, die dich und dein Team im AI-Zeit-Operating schnell aufleveln." },
      { label: "03", name: "AI-Operations", site: "blankcollar.ai", voice: "bot", description: "Wir konfigurieren dein agentisches OS, damit das Wissen als Automation läuft, nicht als Ratschlag." },
      { label: "04", name: "Kapital-Zugang", site: "blankcollar.ventures", voice: "human", description: "Warme Intros zu den VCs, mit denen wir arbeiten — direkt, wenn du bereit bist zu raisen.", current: true },
    ],
  },
  tiers: {
    eyebrow: "04 — So arbeiten wir",
    h1: "Zwei Wege, wie wir arbeiten.",
    h2: "Wir wählen, was passt.",
    sub1: "Jeder Gründer, mit dem wir arbeiten, bekommt das Wissen von theblankcollar.com, die Kurse auf blankcollar.university und einen konfigurierten Zugang zu blankcollar.ai. Wie hands-on wir beim Raise werden — und welche VCs wir öffnen — hängt von deiner Phase ab. Wir entscheiden nach deiner Bewerbung, was passt.",
    cards: [
      {
        id: "access",
        name: "The Essentials",
        audience: "Für Gründer, die ihren Stand finden",
        capital: "Wissen + OS",
        features: [
          "Voller Zugang zu den theblankcollar.com Playbooks",
          "Konfigurierter Zugang zu blankcollar.ai — deinem agentischen OS",
          "Kurse auf blankcollar.university",
          "Pitch Deck, Data Room, Geschäftsmodell — gemeinsam gebaut",
        ],
      },
      {
        id: "full-stack",
        name: "The Full Stack",
        audience: "Für Gründer, die bereit sind zu raisen",
        capital: "Alles + VC-Zugang",
        features: [
          "Alles aus The Essentials",
          "Wir fahren den Raise mit dir, hands-on",
          "Warme Intros zu den VCs, mit denen wir arbeiten",
          "Follow-on-Begleitung durch Seed / Series A",
        ],
        emphasis: true,
      },
    ],
    ctaBody: "Nicht sicher, was passt? Genau dafür ist die Bewerbung da — sag uns, was du baust, und wir melden uns mit unserer Einschätzung.",
    ctaLink: "Sende deine Bewerbung",
  },
  toolkit: {
    eyebrow: "05 — Das First-Time-Gründer-Toolkit",
    h1: "Die schweren Sachen,",
    h2: "die du nicht allein lösen musst.",
    sub1: "Acht Module, die wir in den ersten Wochen mit dir bauen. Wir teilen, was wir gelernt haben, lehren es auf ",
    sub2: ", und verdrahten es dann in deine ",
    sub3: " Agents — damit es weiter wirkt.",
    items: [
      { label: "Pitch Deck", body: "Story-Bogen, Deck-Design, die sieben Slides, die jeder Fonds wirklich liest." },
      { label: "Data Room", body: "Cap Table, Verträge, KPIs, Hiring-Docs — sauber von Tag eins." },
      { label: "Geschäftsmodell", body: "Pricing, Unit Economics, woher die Marge wirklich kommt." },
      { label: "Cap Table & SAFEs", body: "Founder-Splits, Pool, Conversions — saubere Equity ab dem ersten Ticket." },
      { label: "Fundraising-Plan", body: "Zielliste, Reihenfolge, das richtige Narrativ pro Fonds." },
      { label: "Hiring-Playbook", body: "Stellenanzeigen, Comp-Benchmarks, woher die ersten 5 Hires kommen." },
      { label: "Customer Discovery", body: "Interview-Skript, was zu ignorieren ist, wann man aufhören soll zu reden." },
      { label: "Pricing & Packaging", body: "Tiers, Anchoring, die Pricing-Page, die konvertiert." },
    ],
  },
  network: {
    eyebrow: "06 — In der Praxis",
    h1: "Du im Zentrum.",
    h2: "Wissen rund um dich.",
    h3: "Agents im OS.",
    p: "Vom ersten Tag an rätst du nicht mehr. Wir teilen, was über zehn Bereiche hinweg funktioniert, die jeder Gründer irgendwann braucht — und konfigurieren deine Agents auf ",
    p2: ", damit das Wissen als Automation läuft.",
    knowledgeLabel: "Wissen",
    knowledgeBody: " — Pitch Deck, Data Room, Geschäftsmodell, Fundraising, Hiring, Sales, Pricing, Finance, Legal, Brand.",
    agentsLabel: "Agents",
    agentsBody: " — Research, Outreach, Ops, Reporting, Support. Konfiguriert auf deinen Stack.",
    legendKnowledge: "Wissen, das wir teilen (Mensch)",
    legendAgents: "Agents, die wir einrichten (Bot)",
    knowledgeNodes: ["Pitch Deck", "Data Room", "Geschäftsmodell", "Fundraising", "Hiring", "Sales", "Pricing", "Finance", "Legal", "Brand"],
    agentNodes: ["agent.research", "agent.outreach", "agent.ops", "agent.report", "agent.support"],
    centerLabel: "GRÜNDER",
    centerSub: "● DU",
  },
  process: {
    eyebrow: "07 — Prozess",
    h1: "Kein Deck. Keine warme Vorstellung.",
    h2: "Fünf Schritte. Zwei Wochen.",
    steps: [
      { n: "01", label: "Bewerben", body: "Schick uns einen Absatz und einen Link. Kein Deck nötig, keine warme Vorstellung.", detail: "~5 Min." },
      { n: "02", label: "Entscheidung", body: "Wir antworten in maximal 14 Tagen. Ja, nein, oder ein ehrlicher Grund warum.", detail: "≤ 14 Tage" },
      { n: "03", label: "Wissen & Kurse", body: "Das Denken von theblankcollar.com und die Kurse von blankcollar.university — ab Woche eins.", detail: "Woche 1" },
      { n: "04", label: "OS konfiguriert", body: "Wir richten blankcollar.ai für dich ein. Deine Agents, dein Speicher, unser Wissen — kodifiziert.", detail: "Gratis, für immer" },
      { n: "05", label: "Warme Intros", body: "Wenn du fundable bist, öffnen wir die Türen zu den VCs, mit denen wir arbeiten — direkt, nicht über ein Portal.", detail: "Wenn bereit" },
    ],
    stepLabel: "Schritt",
  },
  compare: {
    eyebrow: "08 — vs. klassisches Pre-Seed",
    h1: "Kein Fonds.",
    h2: "Ein Zugang.",
    sub: "Klassisches Pre-Seed-Geld kommt mit einem Quartals-Check-in. Wir kommen mit Wissen, AI-Setup, Upskilling — und der Vorstellung, die dir das Geld überhaupt erst bringt.",
    headerFeature: "Aspekt",
    headerTrad: "Klassisches Pre-Seed",
    headerUs: "blankcollar.ventures",
    rows: [
      { feature: "Kapital", trad: "Ihr Cheque, frühe Verwässerung", us: "Warme Intros zu den VCs, mit denen wir arbeiten" },
      { feature: "Entscheidungszeit", trad: "Wochen voller Meetings", us: "Maximal 14 Tage" },
      { feature: "Nach dem Ja", trad: "Quartalsweise Check-ins", us: "Hands-on, bis du fundable bist" },
      { feature: "Pitch Deck & Data Room", trad: "„Schickt es uns, wenn ihr soweit seid“", us: "In Woche eins gemeinsam gebaut" },
      { feature: "Geschäftsmodell-Hilfe", trad: "Vorstellungen zu Beratern", us: "Pricing, Unit Economics, Moats" },
      { feature: "KI / Automation", trad: "„Habt ihr ChatGPT mal probiert?“", us: "Wir richten blankcollar.ai für dich ein" },
      { feature: "Upskilling", trad: "Findest du selbst heraus", us: "Kurse auf blankcollar.university" },
      { feature: "Hiring-Hilfe", trad: "Vorstellungen zu Recruitern", us: "Playbooks, Stellenanzeigen, Comp-Benchmarks" },
      { feature: "Netzwerk", trad: "LP-Vorstellungen", us: "Direkte Intros zu den VCs, mit denen wir arbeiten" },
    ],
    inlineTradLabel: "Klassisch ·",
  },
  portfolio: {
    eyebrow: "09 — Portfolio",
    h1: "Gründer, die wir geholfen haben",
    h2: "von Anfang bis Ende zu skalieren.",
    sub1: "Fünf Schweizer / EU-Unternehmen, gebaut auf demselben Playbook: Wissen, AI-Operations, Upskilling und die Intros, die zählten — ab Tag eins eingebaut. ",
    sub2: "Ein Exit bisher. Vier weiter im Steigen.",
    statusActive: "Aktiv",
    statusExited: "Exited",
    companies: [
      { name: "Numarics", domain: "numarics.com", url: "https://numarics.com", category: "Fintech / Buchhaltung", body: "AI-natives Accounting für KMU und Treuhand. Gebaut, skaliert, verkauft — treibt jetzt seinen Nachfolger Money Key an.", origin: "CH", status: "exited" as const },
      { name: "Cybee.ai", domain: "cybee.ai", url: "https://cybee.ai", category: "Cybersecurity", body: "Cybersecurity & Compliance für KMU. SOC 2, GDPR, ISO 27001 — automatisiert, in Klartext.", origin: "CH", status: "active" as const },
      { name: "iQTax", domain: "iqtax.ch", url: "https://iqtax.ch", category: "AI Tax", body: "Die KI-Plattform für Schweizer Steuererklärungen. Hochladen, einreichen, fertig — in Minuten, nicht Stunden.", origin: "CH", status: "active" as const },
      { name: "Alletta", domain: "alletta.ch", url: "https://alletta.ch", category: "InsurTech", body: "Die erste vollständig digitale, KI-gestützte Plattform für Kranken- und Rechtsschutzversicherungen in der Schweiz.", origin: "CH", status: "active" as const },
      { name: "Visorway", domain: "visorway.ai", url: "https://visorway.ai", category: "AI Consulting", body: "AI-natives Consulting. Ein KI-Berater vor vollwertigen IT- und ESG-Beratungs-Engines.", origin: "EU", status: "active" as const },
    ],
  },
  netSection: {
    eyebrow: "10 — Zugang",
    h1: "Wir kennen viele",
    h2: "Investoren.",
    p1: "Kein Sales-Pitch — es ist der Punkt. Nach Jahren des Aufbauens und Verkaufens unserer eigenen Startups haben wir die Kontakte behalten: Seed-Fonds, Series A, Family Offices, die richtigen Angels.",
    p2: "Wir schreiben den Cheque nicht selbst. Aber wenn du fundable bist, machen wir warme Vorstellungen zu den richtigen Leuten — direkt, nicht über ein Portal. So raisen unsere Gründer.",
    stats: [
      { n: "Direkt", label: "Beziehungen, kein Portal" },
      { n: "Pre-Seed → B", label: "Über alle Folgerunden hinweg" },
      { n: "Nur warm", label: "Wir machen die Vorstellung, nicht du" },
    ],
  },
  terms: {
    eyebrow: "11 — Konditionen",
    h1: "Was du bekommst,",
    h2: "auf den Punkt.",
    rows: [
      { k: "Unser Cheque", v: "Wir schreiben keinen" },
      { k: "Was du bekommst", v: "Wissen, AI-Ops, Upskilling" },
      { k: "Kapital", v: "Warme Intros zu Partner-VCs" },
      { k: "Phase", v: "Pre-Seed / Tag 0" },
      { k: "Geografie", v: "Global, remote-first" },
      { k: "Tempo", v: "Entscheidung in 14 Tagen" },
    ],
  },
  cta: {
    badge: "Wir prüfen aktuell Bewerbungen",
    h1a: "Baust",
    h1b: "du was?",
    h2a: "Wir helfen",
    h2b: "gerne.",
    sub: "Ein Absatz, ein Link. Wenn es passt, gehen wir schnell — Wissen, AI, Upskilling und die Vorstellung, bereit zum Einsatz.",
    primary: "Bewerbung starten",
    secondary: "Portfolio ansehen",
  },
  footer: {
    tagline: "Der Ventures-Arm der blankcollar Familie. Wissen, AI-Operations, Upskilling und Zugang zu den VCs, mit denen wir arbeiten.",
    family: "Familie",
    page: "Seite",
    contact: "Kontakt",
    pageItems: ["Manifest", "Stack", "Toolkit", "Portfolio", "Konditionen"],
    motto: "Arbeit ist für Bots. Leben ist für Menschen.",
  },
  apply: {
    eyebrow: "Bewerbung",
    title: "Sag uns, was du baust.",
    sub: "~7 Minuten. Speichert automatisch. Wir antworten in maximal 14 Tagen — ja, nein, oder ein ehrlicher Grund.",
    sectionsLabels: { you: "Du", team: "Team", company: "Unternehmen", vision: "Vision", ask: "Bedarf", materials: "Material", review: "Überprüfen" },
    stepOf: "Schritt",
    of: "von",
    feedback: {
      basics: "Kurze Basics, dann kommt das Spannende.",
      superpower: "Wähle eine oder zwei — was du wirklich mitbringst.",
      team: "Teams, die schon zusammen gearbeitet haben, performen ~3:1 besser im Pre-Seed. Disqualifiziert niemanden — nur nützliche Farbe.",
      pitch: "Starke One-Liner schlagen oft schwerer als ihr Gewicht. Investiere zwei Minuten extra hier.",
      whyNow: "Die Frage „Warum jetzt“ trennt fund-grade von forever-startup.",
      risk: "Die ehrliche Antwort signalisiert Selbstwahrnehmung — genau das suchen wir.",
      ask: "Wir können in 14 Tagen entscheiden — wenn die Basics passen.",
      helpFit: "Das ist ein Hinweis, keine Wahl. Wir entscheiden den passenden Tier nach deiner Bewerbung.",
    },
    review: {
      title: "Schau drüber.",
      sub: "Letzte Chance, etwas zu ändern. Lade dein Pitch Deck hoch, falls du eines hast.",
      uploadLabel: "Pitch Deck (Datei-Upload)",
      submit: "Bewerbung absenden →",
    },
    confirm: {
      received: "Bewerbung erhalten",
      thanks: (firstName: string) => `Danke, ${firstName || "Gründer"}.`,
      bodyPre: "Wir haben deine Bewerbung für ",
      bodyMid: " erhalten. Eine Bestätigung wurde an ",
      bodyEnd: " gesendet.",
      timeline: [
        { n: "Tag 1–3", label: "Lesen", body: "Wir lesen jede Bewerbung. Keine Deck-Vorlagen, keine Bots, die dich bewerten." },
        { n: "Tag 3–10", label: "Gespräch", body: "Wenn es Signal gibt, buchen wir ein 30-Minuten-Call. Kamera optional." },
        { n: "Tag 14", label: "Entscheidung", body: "Ja / nein / ehrlicher Grund. Wenn ja, starten wir am nächsten Morgen." },
      ],
      whileYouWait: "Solange du wartest — ",
      whileItems: [
        { title: "theblankcollar.com", body: "Sieh die Wissens-Ebene in Aktion.", href: "https://www.theblankcollar.com" },
        { title: "blankcollar.ai", body: "Schau dir das agentische OS an, das wir für dich einrichten.", href: "https://www.blankcollar.ai" },
        { title: "blankcollar.university", body: "Die Kurse, auf die wir dich hinweisen.", href: "https://www.blankcollar.university" },
        { title: "Portfolio", body: "Gründer, denen wir bereits geholfen haben.", href: "/de#portfolio" },
      ],
      replyNote: " Wenn etwas Dringendes auftaucht, antworte einfach auf die Bestätigungsmail. Sie kommt aus einem echten Posteingang.",
    },
    steps: {
      you1: "Sag uns, wer du bist.",
      you2: "Was ist deine Superkraft?",
      team: "Wer baut das mit dir auf?",
      company: "Das Unternehmen.",
      stage: "Wo stehst du auf der Kurve?",
      sectorPitch: "Sektor und der Elevator Pitch.",
      problem: "Das Problem, das du löst.",
      solution: "Was du baust, und warum jetzt.",
      whyNow: "Warum jetzt?",
      traction: "Kundengespräche + Traction.",
      risk: "Was ist gerade dein grösstes Risiko?",
      ask: "Die Runde und was sie bewirken wird.",
      helpFit: "Welche Art Hilfe passt zu dir?",
      materials: "Zeig uns, was du hast.",
    },
    fields: {
      yourName: { label: "Dein Name", placeholder: "Max Muster" },
      email: { label: "E-Mail", hint: "Damit erreichen wir dich ab jetzt.", placeholder: "max@deinstartup.com" },
      yourRole: { label: "Deine Rolle", placeholder: "CEO, CTO, Founder…" },
      location: { label: "Wo bist du", hint: "Stadt, Land.", placeholder: "Zürich, CH" },
      linkedin: { label: "LinkedIn", placeholder: "https://linkedin.com/in/…" },
      workedTogether: { label: "Wie lange arbeitet ihr schon zusammen?" },
      teamDescription: { label: "Erzähl uns vom Team", hint: "Co-Founder, Schlüsselrollen, wer ist Vollzeit. Eine Zeile pro Person.", placeholder: "z.B.\nMax — CEO, ex-Stripe (FT)\nMarc — CTO, ex-Google (FT)\nWir suchen einen Designer." },
      companyName: { label: "Firmenname", placeholder: "Stripe, Linear, …" },
      companyWebsite: { label: "Website", placeholder: "https://deinstartup.com" },
      sector: { label: "Sektor" },
      oneLiner: { label: "One-Liner Elevator Pitch", hint: "Wenn ein Fremder es einem Freund weitererzählen müsste — was würde er sagen?", placeholder: '"Stripe für Cross-Border-Payroll in Afrika."' },
      problem: { label: "Das Problem", hint: "Auf den Punkt. Was ist kaputt, und warum hat es noch keiner gelöst?" },
      customer: { label: "Wer hat dieses Problem", hint: "Sei konkret beim Kunden.", placeholder: "z.B. 'CFOs bei Series A SaaS-Firmen in Europa mit 20–80 Mitarbeitenden'" },
      solution: { label: "Deine Lösung", hint: "Was baust du, einfach erklärt?" },
      differentiator: { label: "Was ist anders", hint: "Warum wird der naheliegende Platzhirsch dich nicht zermalmen?" },
      whyNow: { label: "Warum ist jetzt der richtige Moment dafür?", hint: "Tech-Shift, Regulierung, Verhaltensänderung, KI-Wendepunkt — was ist der Katalysator?" },
      interviews: { label: "Wie viele Kundengespräche hast du geführt?", hint: "Null ist eine ehrliche Antwort — wir wollen die Wahrheit." },
      traction: { label: "Bisherige Traction", hint: "Umsatz, Signups, Design Partners, LOIs, Waitlist — alles Echte zählt." },
      raisingAmount: { label: "Wie viel sammelst du in dieser Runde", hint: "Die Runde, die du aufnehmen willst.", placeholder: "z.B. CHF 250'000" },
      useOfFunds: { label: "Wofür wird das Geld verwendet", hint: "Top 3 Posten." },
      helpFit: { label: "Deine Einschätzung, was passt" },
      whyUs: { label: "Warum blankcollar konkret", hint: "Keine falsche Antwort. Sei einfach ehrlich." },
      pitchDeckLink: { label: "Pitch Deck Link", hint: "Notion, Pitch, Google Slides, Loom — was auch immer du hast." },
      productLink: { label: "Produkt- / Demo-Link" },
      somethingElse: { label: "Sonst noch etwas, das wir wissen sollten" },
    },
    cards: {
      stage: {
        "pre-incorporation": { label: "Pre-Incorporation", description: "Nur eine Idee, vielleicht ein Prototyp." },
        incorporated: { label: "Gegründet, vor Umsatz", description: "Firma existiert, ihr baut auf den ersten Franken hin." },
        "first-revenue": { label: "Erster Umsatz", description: "Echte Kunden, echtes (kleines) Geld." },
        scaling: { label: "Skalierung", description: "Wiederholbarer Umsatz, Hiring, Geschwindigkeit." },
      },
      worked: {
        "first-time": { label: "Zum ersten Mal", description: "Wir haben uns gerade zusammengefunden." },
        "less-than-6m": { label: "< 6 Monate", description: "Frühe Tage zusammen." },
        "6m-to-2y": { label: "6 Monate – 2 Jahre", description: "Unter Druck getestet." },
        "over-2y": { label: "2+ Jahre", description: "Wir haben einiges durchgemacht." },
      },
      sector: {
        "ai-ml": "AI / ML",
        fintech: "Fintech",
        healthtech: "Healthtech",
        climate: "Climate",
        devtools: "Dev Tools",
        consumer: "Consumer",
        "b2b-saas": "B2B SaaS",
        other: "Anderes",
      },
      superpower: {
        story: { label: "Storytelling", description: "Ich verkaufe die Vision. Leute folgen." },
        tech: { label: "Engineering", description: "Ich shippe das Produkt." },
        sales: { label: "Sales & GTM", description: "Ich schliesse Deals. Ich fahre den Playbook." },
        ops: { label: "Operations", description: "Ich sorge dafür, dass alles pünktlich läuft." },
        vision: { label: "Vision & Strategie", description: "Ich sehe zwei Züge voraus." },
        network: { label: "Netzwerk", description: "Ich öffne Türen, die andere nicht öffnen können." },
      },
      interview: {
        none: { label: "Noch nicht angefangen", description: "Wir gehen (bisher) nach Instinkt." },
        "1-10": { label: "1 – 10", description: "Frühes Signal, frühe Überzeugung." },
        "10-50": { label: "10 – 50", description: "Echte Mustererkennung." },
        "50-plus": { label: "50+", description: "Tiefe Kundenbesessenheit." },
      },
      risk: {
        demand: { label: "Kunden kaufen nicht", description: "Pull-Risiko." },
        build: { label: "Bauen ist schwer", description: "Tech- / Execution-Risiko." },
        funding: { label: "Geld geht zuerst aus", description: "Runway-Risiko." },
        team: { label: "Team / Hiring", description: "Personen-Risiko." },
        other: { label: "Etwas anderes", description: "Erzähl es uns gleich." },
      },
      helpFit: {
        access: { label: "Wir brauchen den Schub", description: "Wir brauchen das Wissen, die Kurse und das agentische OS." },
        "full-stack": { label: "Wir sind bereit zu raisen", description: "Wir brauchen alles — und warme Intros zu den richtigen VCs." },
      },
    },
    validations: {
      name: "Sag uns deinen Namen",
      email: "E-Mail sieht komisch aus",
      role: "Trag deine Rolle ein",
      location: "Wo bist du?",
      superpower: "Wähle mindestens eine",
      workedTogether: "Wähle eines",
      teamDescription: "Erzähl uns vom Team",
      companyName: "Firmenname",
      stage: "Wähle eine Phase",
      sector: "Wähle einen Sektor",
      oneLiner: "Gib uns den One-Liner",
      problem: "Beschreibe das Problem",
      customer: "Wer hat dieses Problem?",
      solution: "Was baust du?",
      differentiator: "Was ist anders?",
      whyNow: "Sag uns, warum jetzt",
      interviews: "Wähle den passenden Bereich",
      risk: "Wähle das Naheliegendste",
      raisingAmount: "Rundengrösse",
      useOfFunds: "Verwendung der Mittel",
      helpFit: "Sag uns, was passt",
      whyUs: "Sag uns warum",
    },
  },
};

export type Dict = typeof en;

export const dict: Record<Lang, Dict> = { en, de };
